import React, { useState } from 'react';
import {
  Layers,
  HelpCircle,
  AlertTriangle,
  FileText,
  Sparkles,
  Download,
  Share2,
  Check,
  Send,
  PlusCircle,
  Bookmark,
} from 'lucide-react';
import type {
  StudyDeck,
  StudyMode,
  CardMastery,
  QuizProgress,
} from '../types/result';

import { FlashcardDeck } from './FlashcardDeck';
import { QuizView } from './QuizView';
import { WeakSpotsView } from './WeakSpotsView';

interface ResultViewProps {
  deck: StudyDeck;
  providerUsed?: string;
  onRefine: (refinementPrompt: string) => void;
  isRefining: boolean;
  onSaveSession: () => void;
  isSessionSaved: boolean;
}

export const ResultView: React.FC<ResultViewProps> = ({
  deck,
  providerUsed,
  onRefine,
  isRefining,
  onSaveSession,
  isSessionSaved,
}) => {
  const [activeMode, setActiveMode] = useState<StudyMode>('flashcards');
  const [mastery, setMastery] = useState<CardMastery>({});
  const [quizProgress, setQuizProgress] = useState<QuizProgress>({});
  const [refinementInput, setRefinementInput] = useState('');
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  // Update card mastery
  const handleUpdateMastery = (cardId: string, status: 'mastered' | 'review') => {
    setMastery(prev => ({
      ...prev,
      [cardId]: status,
    }));
  };

  const handleResetMastery = () => {
    setMastery({});
  };

  // Update quiz question progress
  const handleAnswerQuestion = (questionId: string, selectedIndex: number, isCorrect: boolean) => {
    setQuizProgress(prev => ({
      ...prev,
      [questionId]: { selectedIndex, isCorrect },
    }));
  };

  const handleResetQuiz = () => {
    setQuizProgress({});
  };

  const handleRetestWrong = (wrongIds: string[]) => {
    setQuizProgress(prev => {
      const updated = { ...prev };
      wrongIds.forEach(id => delete updated[id]);
      return updated;
    });
  };

  // Refinement submit
  const handleRefineSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!refinementInput.trim() || isRefining) return;
    onRefine(refinementInput.trim());
    setRefinementInput('');
  };

  // Export deck as JSON
  const handleExportJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(deck, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${deck.topic.toLowerCase().replace(/\s+/g, '-')}-study-deck.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  // Export / copy markdown notes
  const handleCopyMarkdown = () => {
    let md = `# Study Deck: ${deck.topic}\n\n`;
    md += `> ${deck.summary}\n\n`;
    md += `## Key Takeaways\n`;
    deck.keyTakeaways.forEach(k => {
      md += `- ${k}\n`;
    });
    md += `\n## Flashcards\n`;
    deck.cards.forEach((c, idx) => {
      md += `### ${idx + 1}. ${c.question}\n**Answer:** ${c.answer}\n*Explanation:* ${c.explanation}\n\n`;
    });
    md += `## Quiz Assessment\n`;
    deck.quiz.forEach((q, idx) => {
      md += `### Q${idx + 1}: ${q.question}\n`;
      q.options.forEach((opt, oIdx) => {
        md += `- [${oIdx === q.correctIndex ? 'x' : ' '}] ${opt}\n`;
      });
      md += `*Explanation:* ${q.explanation}\n\n`;
    });

    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2500);
  };

  // Count items needing review
  const reviewCardsCount = deck.cards.filter(c => mastery[c.id] === 'review').length;
  const wrongQuizCount = deck.quiz.filter(q => quizProgress[q.id] && !quizProgress[q.id].isCorrect).length;
  const totalWeakSpots = reviewCardsCount + wrongQuizCount;

  return (
    <div className="result-view-container">
      {/* Top Deck Info Header */}
      <div className="deck-info-banner glass-card">
        <div className="deck-title-area">
          <div className="deck-topic-row">
            <h1 className="deck-topic-title">{deck.topic}</h1>
            {providerUsed && (
              <span className="deck-provider-pill" title="Generated by LLM provider">
                Provider: {providerUsed}
              </span>
            )}
          </div>
          <p className="deck-summary-text">{deck.summary}</p>
        </div>

        {/* Global actions: Save session, Export JSON, Copy Markdown */}
        <div className="deck-header-actions">
          <button
            type="button"
            className={`btn-action ${isSessionSaved ? 'btn-saved' : ''}`}
            onClick={onSaveSession}
            title="Save this deck in browser local storage"
          >
            <Bookmark size={15} />
            <span>{isSessionSaved ? 'Deck Saved' : 'Save Session'}</span>
          </button>

          <button
            type="button"
            className="btn-action"
            onClick={handleExportJson}
            title="Download structured JSON"
          >
            <Download size={15} />
            <span>JSON</span>
          </button>

          <button
            type="button"
            className="btn-action"
            onClick={handleCopyMarkdown}
            title="Copy as Markdown Study Sheet"
          >
            {copiedMarkdown ? <Check size={15} className="text-success" /> : <Share2 size={15} />}
            <span>{copiedMarkdown ? 'Copied MD' : 'Copy MD'}</span>
          </button>
        </div>
      </div>

      {/* Mode Navigation Tabs */}
      <div className="mode-nav-tabs">
        <button
          type="button"
          className={`mode-tab ${activeMode === 'flashcards' ? 'active-mode' : ''}`}
          onClick={() => setActiveMode('flashcards')}
        >
          <Layers size={18} />
          <span>Flashcard Deck</span>
          <span className="tab-count">{deck.cards.length}</span>
        </button>

        <button
          type="button"
          className={`mode-tab ${activeMode === 'quiz' ? 'active-mode' : ''}`}
          onClick={() => setActiveMode('quiz')}
        >
          <HelpCircle size={18} />
          <span>Knowledge Quiz</span>
          <span className="tab-count">{deck.quiz.length}</span>
        </button>

        <button
          type="button"
          className={`mode-tab ${activeMode === 'weakspots' ? 'active-mode' : ''}`}
          onClick={() => setActiveMode('weakspots')}
        >
          <AlertTriangle size={18} />
          <span>Weak Spots</span>
          {totalWeakSpots > 0 && <span className="tab-count-alert">{totalWeakSpots}</span>}
        </button>

        <button
          type="button"
          className={`mode-tab ${activeMode === 'notes' ? 'active-mode' : ''}`}
          onClick={() => setActiveMode('notes')}
        >
          <FileText size={18} />
          <span>Key Notes & Summary</span>
        </button>
      </div>

      {/* Main View Area */}
      <div className="mode-content-area">
        {activeMode === 'flashcards' && (
          <FlashcardDeck
            cards={deck.cards}
            mastery={mastery}
            onUpdateMastery={handleUpdateMastery}
            onResetMastery={handleResetMastery}
          />
        )}

        {activeMode === 'quiz' && (
          <QuizView
            questions={deck.quiz}
            quizProgress={quizProgress}
            onAnswerQuestion={handleAnswerQuestion}
            onResetQuiz={handleResetQuiz}
            onRetestWrong={handleRetestWrong}
          />
        )}

        {activeMode === 'weakspots' && (
          <WeakSpotsView
            cards={deck.cards}
            quiz={deck.quiz}
            mastery={mastery}
            quizProgress={quizProgress}
            onSwitchToFlashcards={() => setActiveMode('flashcards')}
            onSwitchToQuiz={() => setActiveMode('quiz')}
            onRefineWeakSpots={(customPrompt) => {
              onRefine(customPrompt);
            }}
          />
        )}

        {activeMode === 'notes' && (
          <div className="notes-view glass-card">
            <h3 className="notes-heading">Executive Topic Summary</h3>
            <p className="notes-summary">{deck.summary}</p>

            <h4 className="takeaways-heading">Key Concept Takeaways</h4>
            <ul className="takeaways-list">
              {deck.keyTakeaways.map((takeaway, idx) => (
                <li key={idx} className="takeaway-item">
                  <div className="takeaway-bullet">{idx + 1}</div>
                  <span>{takeaway}</span>
                </li>
              ))}
            </ul>

            <h4 className="curriculum-heading">Complete Deck Outline</h4>
            <div className="cards-outline-list">
              {deck.cards.map((c, i) => (
                <div key={c.id} className="outline-card-row">
                  <span className="outline-index">#{i + 1}</span>
                  <div className="outline-content">
                    <span className="outline-question">{c.question}</span>
                    <span className="outline-answer">{c.answer}</span>
                  </div>
                  <span className={`diff-pill diff-${c.difficulty}`}>{c.difficulty}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Refinement Loop (Stretch Goal) */}
      <div className="refinement-container glass-card">
        <div className="refinement-header">
          <div className="refinement-title-box">
            <Sparkles size={18} className="text-accent" />
            <h4 className="refinement-title">Refinement Loop (Follow-Up Prompts)</h4>
          </div>
          <span className="refinement-tag">Edits existing deck dynamically</span>
        </div>

        <p className="refinement-description">
          Want more advanced cards, simpler analogies, or questions on a specific sub-topic? Ask the AI to refine this deck.
        </p>

        <form onSubmit={handleRefineSubmit} className="refinement-form">
          <div className="refinement-input-wrapper">
            <input
              type="text"
              className="refinement-input"
              value={refinementInput}
              onChange={e => setRefinementInput(e.target.value)}
              placeholder="e.g. 'Add 3 harder cards on edge cases', 'Make quiz questions more challenging', 'Add code snippet examples'..."
              disabled={isRefining}
            />
            <button
              type="submit"
              className="btn-refine"
              disabled={isRefining || !refinementInput.trim()}
            >
              {isRefining ? (
                <>
                  <span className="spinner-dots" />
                  <span>Refining...</span>
                </>
              ) : (
                <>
                  <Send size={15} />
                  <span>Refine Deck</span>
                </>
              )}
            </button>
          </div>

          <div className="refinement-quick-pills">
            <span className="quick-label">Quick refinements:</span>
            <button
              type="button"
              className="quick-pill"
              onClick={() => onRefine('Add 3 more advanced flashcards covering tricky edge cases and common interview gotchas.')}
              disabled={isRefining}
            >
              <PlusCircle size={12} />
              <span>+3 Advanced Cards</span>
            </button>
            <button
              type="button"
              className="quick-pill"
              onClick={() => onRefine('Simplify all card answers using intuitive real-world analogies suitable for beginners.')}
              disabled={isRefining}
            >
              <PlusCircle size={12} />
              <span>Simplify with Analogies</span>
            </button>
            <button
              type="button"
              className="quick-pill"
              onClick={() => onRefine('Add 2 challenging multiple choice scenario questions to the quiz with detailed explanations.')}
              disabled={isRefining}
            >
              <PlusCircle size={12} />
              <span>+2 Quiz Questions</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
